---
title: "day-16"
author: "Xuefei Gao"
date: "8/31/2020"
output: html_document
---
```{r}
library(tidyverse)
library(sf)
library(USAboundariesData)
library(USAboundaries)
library(readxl)
library(rmapshaper)
library(gghighlight)
library(knitr)
library(leaflet)

USconus = USAboundaries::us_counties() %>%
  filter(!state_name %in% c("Puerto Rico", "Alaska", "Hawaii")) %>%
  st_transform(5070)

USconus_simp = ms_simplify(USconus, keep = 0.1)
conusnpts = mapview::npts(USconus)
simpnpts = mapview::npts(USconus_simp)

dam = read_xlsx("data/NID2019_U.xlsx") %>% 
  filter(!is.na(LONGITUDE), !is.na(LATITUDE)) %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326) %>%
  st_transform(5070) %>%
  st_filter(USconus_simp)
  
MSSP = read_sf("data/majorrivers_0_0") %>% 
  filter(SYSTEM == "Mississippi") %>%
  st_transform(4326)

MaxRisk = dam %>% 
  filter(HAZARD == "H", 
         grepl("C", PURPOSES)) %>%
  group_by(STATE) %>%
  slice_max(NID_STORAGE) %>%
  select("DAM_NAME", "NID_STORAGE", "YEAR_COMPLETED", "PURPOSES") %>% 
  st_transform(4326)

leaflet() %>% 
  addProviderTiles(providers$CartoDB) %>% 
  addPolylines(data = MSSP) %>% 
  addCircleMarkers(data = MaxRisk, 
                   fillOpacity = .5, 
                   radius = ~NID_STORAGE/1500000, 
                   color = "red", 
                   stroke = FALSE,  
                   popup = leafpop::popupTable(st_drop_geometry(MaxRisk), 
                           feature.id = FALSE, 
                           row.number = FALSE))
